/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Connections.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.temporal.ChronoUnit;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author INTEL
 */
public class Register1 extends javax.swing.JFrame {
   Connection conn = null;
PreparedStatement pst=  null;
  ResultSet rs = null;
  
    public Register1() {
        initComponents();
          conn = Database.ConnectDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        voterid = new javax.swing.JTextField();
        UserLevel = new javax.swing.JLabel();
        UserLevel1 = new javax.swing.JLabel();
        UserLevel2 = new javax.swing.JLabel();
        UserLevel8 = new javax.swing.JLabel();
        repass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        UserLevel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        UserLevel5 = new javax.swing.JLabel();
        UserLevel6 = new javax.swing.JLabel();
        UserLevel7 = new javax.swing.JLabel();
        UserLevel4 = new javax.swing.JLabel();
        UserLevel9 = new javax.swing.JLabel();
        UserLevel10 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        pro = new javax.swing.JComboBox<>();
        add = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        munic = new javax.swing.JTextField();
        UserLevel11 = new javax.swing.JLabel();
        gend = new javax.swing.JComboBox<>();
        fn = new javax.swing.JTextField();
        UserLevel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(236, 245, 255));
        jPanel2.setForeground(new java.awt.Color(236, 245, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(461, 506));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Register");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(11, 24, 69));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENTS REGISTRATION FORM");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 570, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEL\\Downloads\\1PICS\\admin1.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEL\\Downloads\\1PICS\\exit.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(188, 255, 221));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voterid.setBackground(new java.awt.Color(255, 255, 255));
        voterid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        voterid.setActionCommand("<Not Set>");
        voterid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        voterid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteridActionPerformed(evt);
            }
        });
        voterid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                voteridKeyTyped(evt);
            }
        });
        jPanel3.add(voterid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 36, 222, 24));

        UserLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel.setText("Username");
        jPanel3.add(UserLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 82, -1, -1));

        UserLevel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel1.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel1.setText("Password");
        jPanel3.add(UserLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 124, -1, -1));

        UserLevel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel2.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel2.setText("Re-type Password");
        jPanel3.add(UserLevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        UserLevel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel8.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel8.setText("Age");
        jPanel3.add(UserLevel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 30, -1));

        repass.setBackground(new java.awt.Color(255, 255, 255));
        repass.setForeground(new java.awt.Color(0, 0, 0));
        repass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        repass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repassActionPerformed(evt);
            }
        });
        jPanel3.add(repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 222, -1));

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 122, 222, -1));

        UserLevel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel3.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel3.setText("Student's ID");
        jPanel3.add(UserLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        user.setActionCommand("<Not Set>");
        user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 222, 24));

        UserLevel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel5.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel5.setText("Last Name");
        jPanel3.add(UserLevel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 38, -1, -1));

        UserLevel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel6.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel6.setText("First Name");
        jPanel3.add(UserLevel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 72, -1, 37));

        UserLevel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel7.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel7.setText("Middle Name");
        jPanel3.add(UserLevel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        UserLevel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        UserLevel4.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel4.setText("if grade 10 and below please input 'none''");
        jPanel3.add(UserLevel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        UserLevel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel9.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel9.setText("Section");
        jPanel3.add(UserLevel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        UserLevel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel10.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel10.setText("Year Level");
        jPanel3.add(UserLevel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        ln.setBackground(new java.awt.Color(255, 255, 255));
        ln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ln.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel3.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 35, 222, 30));

        mn.setBackground(new java.awt.Color(255, 255, 255));
        mn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnActionPerformed(evt);
            }
        });
        jPanel3.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 222, 30));

        pro.setBackground(new java.awt.Color(188, 255, 221));
        pro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRADE 4", "GRADE 5", "GRADE 6", "GRADE 7", "GRADE 8", "GRADE 9", "GRADE 10", "GRADE 11", "GRADE 12", " " }));
        pro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jPanel3.add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 222, -1));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, 24));

        age.setBackground(new java.awt.Color(255, 255, 255));
        age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 76, 24));

        munic.setBackground(new java.awt.Color(255, 255, 255));
        munic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        munic.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        munic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        munic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municActionPerformed(evt);
            }
        });
        jPanel3.add(munic, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 222, 24));

        UserLevel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel11.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel11.setText("Gender");
        jPanel3.add(UserLevel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        gend.setBackground(new java.awt.Color(188, 255, 221));
        gend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMALE", "MALE" }));
        jPanel3.add(gend, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 144, -1));

        fn.setBackground(new java.awt.Color(255, 255, 255));
        fn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 222, 30));

        UserLevel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel12.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel12.setText("Strand");
        jPanel3.add(UserLevel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(36, 36, 36)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String voter = voterid.getText();
        String username = user.getText();
        String password = pass.getText();
        String retry = repass.getText();
        String birth = age.getText();
         
        if( voterid.getText().length() <=9){
              JOptionPane.showMessageDialog(null, "Student ID must be 10 characters only. Try again","Fill",JOptionPane.ERROR_MESSAGE);
       }
        
        else if (username.equals("") )
        {
            JOptionPane.showMessageDialog(null, "Add a Username!","Fill",JOptionPane.ERROR_MESSAGE);
        }else if (voter.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Student's ID!","Fill",JOptionPane.ERROR_MESSAGE);
        }
           else if (password.equals("") )
        {
            JOptionPane.showMessageDialog(null, "Add a Password!","Fill",JOptionPane.ERROR_MESSAGE);
        }  
           else if (ln.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Last Name!","Fill",JOptionPane.ERROR_MESSAGE);
     
        } 
            else if (fn.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Add a First Name!","Fill",JOptionPane.ERROR_MESSAGE);
   
        }  else if (add.getText().equals("") )       
        {
            JOptionPane.showMessageDialog(null, "Add a Course!","Fill",JOptionPane.ERROR_MESSAGE);
        } else if (munic.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Add a Section!","Fill",JOptionPane.ERROR_MESSAGE);
        }
      
         else if (birth.equals("")  )
        {
            JOptionPane.showMessageDialog(null, "Add an Age!","Fill",JOptionPane.ERROR_MESSAGE);
        }
        else if (checkbday(birth)){
            JOptionPane.showMessageDialog(null, "Only grade 4 students and up can vote.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if (!password.equals(retry) )
        {
            JOptionPane.showMessageDialog(null, "The password and Re-type Password doesn't match. Please try again.","ERROR",JOptionPane.ERROR_MESSAGE);     
        } 
        else if (retry.equals("") )
        {
            JOptionPane.showMessageDialog(null, "Add a Re-type Password!","Fill",JOptionPane.ERROR_MESSAGE);
        }   else if (checkVoterID(voter) )       
        {
            JOptionPane.showMessageDialog(null, "There's already a student who is registered with this ID.","ERROR",JOptionPane.ERROR_MESSAGE);
        } 
        else if (checkUsername(username) )       
        {
            JOptionPane.showMessageDialog(null, "This username is already occupied.","ERROR",JOptionPane.ERROR_MESSAGE);
        }   
        else {
            try{String hi = "INSERT INTO user (studentid,username,pass,age,gender,lastname,firstname,middlename,course,section,year,vote_count) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
           pst= conn.prepareStatement(hi);
            pst.setString(1, voter);
           pst.setString(2, username);
           pst.setString(3, password);
           pst.setString(4,birth);
           pst.setString(5, gend.getSelectedItem().toString());
          pst.setString(6, ln.getText().toUpperCase());
           pst.setString(7, fn.getText().toUpperCase());
           pst.setString(8, mn.getText().toUpperCase());
           pst.setString(9, add.getText().toUpperCase());
            pst.setString(10, munic.getText().toUpperCase());
            pst.setString(11,pro.getSelectedItem().toString());
            pst.setInt(12,0);
            if(pst.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Student's log in details has been added.");
                voterid.setText("");
                user.setText("");
                pass.setText("");
                repass.setText("");
                age.setText("");
                fn.setText("");
                ln.setText("");
                mn.setText("");
                add.setText("");
                munic.setText("");
                
            }        
        
            } catch(Exception ex){
           System.out.println(ex.getMessage());
       }      
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void voteridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voteridActionPerformed

    private void repassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repassActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void municActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void voteridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voteridKeyTyped

char enter = evt.getKeyChar();
  boolean max = voterid.getText().length() >=10;
        if(!(Character.isDigit(enter)) || max){
            
                  evt.consume();
            
          
        }//// TODO add your handling code here:
    }//GEN-LAST:event_voteridKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped

char enter = evt.getKeyChar();
  boolean max = age.getText().length() >=2;
        if(!(Character.isDigit(enter)) || max){
            
                  evt.consume();
            
          
        }//// TODO add your handling code here:
    }//GEN-LAST:event_ageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register1().setVisible(true);
            }
        });
    }
  public boolean checkbday(String birth){
         int a;
        
        ResultSet user;
        boolean checkUserID = false;
      a =Integer. parseInt(birth); 
         
        try{
                      long years = a;
            if (years<=8)
            {
                checkUserID = true;
            }
         
        }catch(Exception ex){
           System.out.println(ex.getMessage());
    }
        return checkUserID;
    } 
    
     public boolean checkVoterID(String voter){
         
        PreparedStatement cc;
        ResultSet user;
        boolean checkUserID = false;
        String no ="SELECT * FROM user WHERE studentid=?";
        try{
            cc = Database.ConnectDatabase().prepareStatement(no);
            cc.setString(1, voter);
            user = cc.executeQuery();
            if (user.next())
            {
                checkUserID = true;
            }
         
        }catch(SQLException ex){
          java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        return checkUserID;
    } 
     
      public boolean checkUsername(String username){
        PreparedStatement cc;
        ResultSet user;
        boolean checkUser = false;
        String no ="SELECT * FROM user WHERE username=?";
        try{
            cc = Database.ConnectDatabase().prepareStatement(no);
            cc.setString(1, username);
            user = cc.executeQuery();
            if (user.next())
            {
                checkUser= true;
            }
         
        }catch(SQLException ex){
          java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        return checkUser;
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserLevel;
    private javax.swing.JLabel UserLevel1;
    private javax.swing.JLabel UserLevel10;
    private javax.swing.JLabel UserLevel11;
    private javax.swing.JLabel UserLevel12;
    private javax.swing.JLabel UserLevel2;
    private javax.swing.JLabel UserLevel3;
    private javax.swing.JLabel UserLevel4;
    private javax.swing.JLabel UserLevel5;
    private javax.swing.JLabel UserLevel6;
    private javax.swing.JLabel UserLevel7;
    private javax.swing.JLabel UserLevel8;
    private javax.swing.JLabel UserLevel9;
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> gend;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField munic;
    private javax.swing.JPasswordField pass;
    private javax.swing.JComboBox<String> pro;
    private javax.swing.JPasswordField repass;
    private javax.swing.JTextField user;
    private javax.swing.JTextField voterid;
    // End of variables declaration//GEN-END:variables
}
