/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Connections.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.*;
import javax.swing.JOptionPane;

public class AddCandidates extends javax.swing.JFrame {

  Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;



    public AddCandidates() {
        initComponents();
         conn = Database.ConnectDatabase();
         populateParty();
        populatePositions();
     
    }
 public void populateParty(){
        try{
            String sql="SELECT name FROM party ORDER BY name ASC";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                party.addItem(rs.getString("name"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    public void populatePositions(){
         try{
            String sql="SELECT name FROM position ORDER BY name ASC";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                position2.addItem(rs.getString("name"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UserLevel5 = new javax.swing.JLabel();
        UserLevel6 = new javax.swing.JLabel();
        UserLevel7 = new javax.swing.JLabel();
        UserLevel10 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        UserLevel11 = new javax.swing.JLabel();
        gend = new javax.swing.JComboBox<>();
        fn = new javax.swing.JTextField();
        pro1 = new javax.swing.JComboBox<>();
        UserLevel12 = new javax.swing.JLabel();
        UserLevel13 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        UserLevel9 = new javax.swing.JLabel();
        party = new javax.swing.JComboBox();
        position2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(188, 255, 221));

        jLabel13.setBackground(new java.awt.Color(15, 30, 84));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(15, 30, 84));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CANDIDATES");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEL\\Downloads\\1PICS\\candidate1.png")); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\INTEL\\Downloads\\1PICS\\exit.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(9, 9, 9))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLevel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel5.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel5.setText("Student's ID");
        jPanel3.add(UserLevel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        UserLevel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel6.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel6.setText("First Name");
        jPanel3.add(UserLevel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 37));

        UserLevel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel7.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel7.setText("Middle Name");
        jPanel3.add(UserLevel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        UserLevel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel10.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel10.setText("Party");
        jPanel3.add(UserLevel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });
        jPanel3.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 222, 30));

        mn.setBackground(new java.awt.Color(255, 255, 255));
        mn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 222, 30));

        UserLevel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel11.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel11.setText("Gender");
        jPanel3.add(UserLevel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        gend.setBackground(new java.awt.Color(188, 255, 221));
        gend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMALE", "MALE" }));
        jPanel3.add(gend, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 144, -1));

        fn.setBackground(new java.awt.Color(255, 255, 255));
        fn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 222, 30));

        pro1.setBackground(new java.awt.Color(188, 255, 221));
        pro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRADE 12", "GRADE 11", "GRADE 10", "GRADE 9", "GRADE 8", "GRADE 7" }));
        pro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 222, -1));

        UserLevel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel12.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserLevel12.setText("Year Level");
        jPanel3.add(UserLevel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, -1));

        UserLevel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel13.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel13.setText("Position");
        jPanel3.add(UserLevel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        ln.setBackground(new java.awt.Color(255, 255, 255));
        ln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ln.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 222, 30));

        UserLevel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserLevel9.setForeground(new java.awt.Color(11, 24, 69));
        UserLevel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel9.setText("Last Name ");
        jPanel3.add(UserLevel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        party.setBackground(new java.awt.Color(188, 255, 221));
        party.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        party.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        party.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyActionPerformed(evt);
            }
        });
        jPanel3.add(party, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 220, -1));

        position2.setBackground(new java.awt.Color(188, 255, 221));
        position2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        position2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        position2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position2ActionPerformed(evt);
            }
        });
        jPanel3.add(position2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 220, -1));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (checkVoterID(ID.getText()) ){
         JOptionPane.showMessageDialog(null, "There is already a student who is registered with this ID.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(ID.getText().equals("") || ln.getText().equals("") || fn.getText().equals("") ||  party.getSelectedIndex()==0 ||  position2.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Please fill up all the required fields!","Fill",JOptionPane.ERROR_MESSAGE);
        }else{
             try{
            String sql = "INSERT INTO candidates_info (studentid,lastname,firstname,middlename,fullname,gender,year,position,party,vote_count) VALUES (?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, ID.getText().toUpperCase());
            pst.setString(2, ln.getText().toUpperCase());
            pst.setString(3, fn.getText().toUpperCase());
            pst.setString(4, mn.getText().toUpperCase());
            pst.setString(5, ln.getText().toUpperCase()+" "+fn.getText().toUpperCase()+" "+mn.getText().toUpperCase());
            pst.setString(6, gend.getSelectedItem().toString().toUpperCase());
            pst.setString(7, pro1.getSelectedItem().toString().toUpperCase());
            pst.setString(8, position2.getSelectedItem().toString().toUpperCase());
            pst.setString(9, party.getSelectedItem().toString().toUpperCase());
            pst.setString(10, "0");
            pst.execute();
            JOptionPane.showMessageDialog(null, "Candidate has been added!");
            
             ID.setText("");
             ln.setText("");
             fn.setText("");
             mn.setText("");
             party.setSelectedIndex(0);
             position2.setSelectedIndex(0);
           
          
                  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry, you can't enter the same candidate!","NO",JOptionPane.ERROR_MESSAGE);
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void partyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partyActionPerformed

    private void position2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_position2ActionPerformed
    
  public boolean checkVoterID(String voter){
         
        PreparedStatement cc;
        ResultSet user;
        boolean checkUserID = false;
        String no ="SELECT * FROM user WHERE studentid=?";
        try{
            cc = Database.ConnectDatabase().prepareStatement(no);
            cc.setString(1, voter);
            user = cc.executeQuery();
            if (user.next())
            {
                checkUserID = true;
            }
         
        }catch(SQLException ex){
          java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        return checkUserID;
    } 

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped

char enter = evt.getKeyChar();
  boolean max = ID.getText().length() >=10;
        if(!(Character.isDigit(enter)) || max){
            
                  evt.consume();   
          
        }//
    }//GEN-LAST:event_IDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCandidates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel UserLevel10;
    private javax.swing.JLabel UserLevel11;
    private javax.swing.JLabel UserLevel12;
    private javax.swing.JLabel UserLevel13;
    private javax.swing.JLabel UserLevel5;
    private javax.swing.JLabel UserLevel6;
    private javax.swing.JLabel UserLevel7;
    private javax.swing.JLabel UserLevel9;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> gend;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mn;
    private javax.swing.JComboBox party;
    private javax.swing.JComboBox position2;
    private javax.swing.JComboBox<String> pro1;
    // End of variables declaration//GEN-END:variables
}
